<?php

function user_theming_theme_suggestions_user(array $variables) {
    return [
        'user__' . $variables['elements']['#view_mode']
    ];
}

function user_theming_theme($existing, $type, $theme, $path) {
    
    return [
        'user__full' => [
          'template' => 'user--full',
          'base hook' => 'user',
        ],
        'user__compact' => [
          'template' => 'user--compact',
          'base hook' => 'user',
        ],
        'user__token' => [
          'template' => 'user--token',
          'base hook' => 'user',
        ],
      ];
    
}

?>