<?php

use Drupal\user\Entity;

/**
 * Implements hook_theme_suggestions_user().
 *
 * Adds user display mode template suggestions.
 * 
 * @inheritdoc
 */
function user_theming_theme_suggestions_user(array $variables) {
  return [
    'user__' . $variables['elements']['#view_mode']
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Adds views template suggestions.
 * 
 * @inheritdoc
 */
function user_theming_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  return [
    'views_view__' . $variables['view']->id()
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Adds views unformatted template suggestions.
 * 
 * @inheritdoc
 */
function user_theming_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
  drupal_set_message('views_view_unformatted__' . $variables['view']->id());
  return [
    'views_view_unformatted__' . $variables['view']->id()
  ];
}

/**
 * Implements hook_theme().
 *
 * Adds user template files to the theme.
 * 
 * @inheritdoc
 */
function user_theming_theme($existing, $type, $theme, $path) {
  return [
    'user__full' => [
      'template' => 'user--full',
      'base hook' => 'user',
    ],
    'user__square_grid' => [
      'template' => 'user--square-grid',
      'base hook' => 'user',
    ],
    'user__inline_grid' => [
      'template' => 'user--inline-grid',
      'base hook' => 'user',
    ],
    'views_view__users_square_grid_views_block' => [
      'template' => 'views-view--users-square-grid-views-block',
      'base hook' => 'views_view',
    ],
    'views_view__users_inline_grid_views_block' => [
      'template' => 'views-view--users-inline-grid-views-block',
      'base hook' => 'views_view',
    ],
    'views_view_unformatted__users_square_grid_views_block' => [
      'template' => 'views-view-unformatted--users-square-grid-views-block',
      'base hook' => 'views_view_unformatted',
    ],
    'views_view_unformatted__users_inline_grid_views_block' => [
      'template' => 'views-view-unformatted--users-inline-grid-views-block',
      'base hook' => 'views_view_unformatted',
    ],
  ];
}

/**
 * Implements hook_preprocess_user().
 *
 * Try to show active user mark.
 * 
 * @inheritdoc
 */
function user_theming_preprocess_user(&$variables) {
  $config = \Drupal::config('user_theming.user_theming_settings');
  $variables['showActiveSessionMark'] = $config->get('show_active_session_mark');
  if ($variables['elements']['#user']->access->value > (time() - 800)) {
    $variables['activeUserMark'] = 1;
  }
  else {
    $variables['activeUserMark'] = 0;
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds our styles library.
 * 
 * @inheritdoc
 */
function user_theming_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'user_theming/styles';
}
